name: Deploy to cPanel
on:
  push:
    branches: [ main ]  # Change to your main branch name if different
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Adjust to match your server's PHP version

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Generate application key
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 755 storage bootstrap/cache

    - name: Configure index.php for deployment
      run: |
        # Make a copy of public/index.php
        cp public/index.php public/index.php.bak
        # Update paths in the public/index.php file
        sed -i 's|require __DIR__.\'/../vendor/autoload.php\';|require __DIR__.\'/../vendor/autoload.php\';|g' public/index.php
        sed -i 's|$app = require_once __DIR__.\'/../bootstrap/app.php\';|$app = require_once __DIR__.\'/../bootstrap/app.php\';|g' public/index.php

    - name: Create additional .htaccess file
      run: |
        echo '<IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /timetable/
            RewriteCond %{REQUEST_URI} !^/timetable/public/
            RewriteRule ^(.*)$ public/$1 [L]
        </IfModule>' > .htaccess

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/timetable/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env.example
